### ISSUE TITLE
[+] New logo of Xiaomi.

### ISSUE THREAD

**Issue by VergeDX** [smileArchitect/wuhan-IT#8]
@smileArchitect [Xiaomi unveils new logo and brand identity](https://www.gsmarena.com/xiaomi_unveils_new_logo-news-48439.php), so I found one on its official site: [logo-mi2.png](https://s02.mifile.cn/assets/static/image/logo-mi2.png).

**Comment by smileArchitect** [comment]
thanks

**Comment by VergeDX** [comment]
Fixed, issues close.
